- en: The Catcher in the… Python. Catch Exceptions and Warnings with One Tool
  id: totrans-0
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 《Python中的接球手… 捕获异常和警告的单一工具》
- en: 原文：[https://towardsdatascience.com/the-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76?source=collection_archive---------19-----------------------#2023-05-23](https://towardsdatascience.com/the-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76?source=collection_archive---------19-----------------------#2023-05-23)
  id: totrans-1
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 原文：[https://towardsdatascience.com/the-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76?source=collection_archive---------19-----------------------#2023-05-23](https://towardsdatascience.com/the-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76?source=collection_archive---------19-----------------------#2023-05-23)
- en: PYTHON PROGRAMMING
  id: totrans-2
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: PYTHON 编程
- en: Why not implement one tool for catching both exceptions and warnings in Python?
  id: totrans-3
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 为什么不实现一个工具来捕获 Python 中的异常和警告呢？
- en: '[](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)[![Marcin
    Kozak](../Images/d7faf62e48ed81dab5d8ad92819fff54.png)](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)[](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)
    [Marcin Kozak](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)'
  id: totrans-4
  prefs: []
  type: TYPE_NORMAL
  zh: '[](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)[![Marcin
    Kozak](../Images/d7faf62e48ed81dab5d8ad92819fff54.png)](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)[](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)[![Towards
    Data Science](../Images/a6ff2676ffcc0c7aad8aaf1d79379785.png)](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)
    [Marcin Kozak](https://medium.com/@nyggus?source=post_page-----81714117da76--------------------------------)'
- en: ·
  id: totrans-5
  prefs: []
  type: TYPE_NORMAL
  zh: ·
- en: '[Follow](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F4762f0cff9b2&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&user=Marcin+Kozak&userId=4762f0cff9b2&source=post_page-4762f0cff9b2----81714117da76---------------------post_header-----------)
    Published in [Towards Data Science](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)
    ·13 min read·May 23, 2023[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2F81714117da76&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&user=Marcin+Kozak&userId=4762f0cff9b2&source=-----81714117da76---------------------clap_footer-----------)'
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: '[关注](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fsubscribe%2Fuser%2F4762f0cff9b2&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&user=Marcin+Kozak&userId=4762f0cff9b2&source=post_page-4762f0cff9b2----81714117da76---------------------post_header-----------)
    发表在 [Towards Data Science](https://towardsdatascience.com/?source=post_page-----81714117da76--------------------------------)
    · 13 min 阅读 · 2023年5月23日 [](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fvote%2Ftowards-data-science%2F81714117da76&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&user=Marcin+Kozak&userId=4762f0cff9b2&source=-----81714117da76---------------------clap_footer-----------)'
- en: --
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: --
- en: '[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2F81714117da76&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&source=-----81714117da76---------------------bookmark_footer-----------)![](../Images/6f42c45eba05eb69d8a1a9adcc012803.png)'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[](https://medium.com/m/signin?actionUrl=https%3A%2F%2Fmedium.com%2F_%2Fbookmark%2Fp%2F81714117da76&operation=register&redirect=https%3A%2F%2Ftowardsdatascience.com%2Fthe-catcher-in-the-python-catch-exceptions-and-warnings-with-one-tool-81714117da76&source=-----81714117da76---------------------bookmark_footer-----------)![](../Images/6f42c45eba05eb69d8a1a9adcc012803.png)'
- en: The article discusses catching exceptions and warnings in Python. Photo by [Keith
    Johnston](https://unsplash.com/de/@acfb5071?utm_source=medium&utm_medium=referral)
    on [Unsplash](https://unsplash.com/?utm_source=medium&utm_medium=referral)
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 这篇文章讨论了在 Python 中捕获异常和警告的内容。图片由 [Keith Johnston](https://unsplash.com/de/@acfb5071?utm_source=medium&utm_medium=referral)
    提供，来自 [Unsplash](https://unsplash.com/?utm_source=medium&utm_medium=referral)
- en: 'Python has some nice approach to handling exceptions. You can catch them, raise
    them, re-raise them, raise two exceptions at the same time (or rather, one exception
    from another), log them, and to create custom errors and their hierarchy, to name
    just the most important ones. If you want to handle warnings, you can also do
    that — but you need two separate tools: one for exceptions and one for warnings.'
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: Python 对处理异常有一些很好的方法。你可以捕获异常、抛出异常、重新抛出异常、同时抛出两个异常（或者更确切地说，从一个异常中抛出另一个异常）、记录它们，并创建自定义错误及其层级，仅举几个最重要的。如果你想处理警告，也可以做到这一点——但你需要两个独立的工具：一个用于异常，另一个用于警告。
- en: Read this article to learn how to write a single catcher for both exceptions
    and warnings, and how to adjust it to your needs.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 阅读这篇文章，了解如何编写一个既能捕获异常也能捕获警告的单一捕获器，以及如何根据你的需求调整它。
- en: 'I really like Python’s exception handling. I like its simplicity, which you
    can see for instance here:'
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 我真的很喜欢 Python 的异常处理。我喜欢它的简单性，例如可以在这里看到：
- en: '[PRE0]'
  id: totrans-13
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
